export const actionTypes = {
  CHANGE_EMAIL: "CHANGE_EMAIL",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_INPUT: "CHANGE_INPUT",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  UPDATE_TODO_LIST: "UPDATE_TODO_LIST",
};
